[tool.poetry]
name = "django-rest-start-template"
version = "0.0.1"
description = "Base template for Django REST application."
authors = ["Dzmitry <dkrukouski@gmail.com>"]

[tool.poetry.dependencies]
python = "^3.10"
Django = "^4.0"
Markdown = "^3.3.4"
django-cors-headers = "^3.11"
django-environ = "^0.8.1"
django-filter = "^21.1"
django-redis = "^5.2"
djangorestframework = "^3.13"
djangorestframework-camel-case = "^1.3"
drf-spectacular = "^0.22"
psycopg2-binary = "^2.9"
sentry-sdk = "^1.5"

[tool.poetry.dev-dependencies]
autopep8 = "^1.6"
django-debug-toolbar = "^3.4"
factory-boy = "^3.2"
flake8 = "^4.0"
flake8-isort = "^4.1"
ipython = "^8.3"
isort = "^5.10"
mypy = "^0.961"
pre-commit = "^2.18"
pytest = "^7.1"
pytest-cov = "^3.0"
pytest-django = "^4.5"
pytest-mock = "^3.7"

[build-system]
build-backend = "poetry.core.masonry.api"
requires = ["poetry-core>=1.0.0"]
