[tool.poetry]
name = "django-rest-start-template"
version = "0.0.1"
description = "Base template for Django REST application."
authors = ["Dzmitry <dkrukouski@gmail.com>"]

[tool.poetry.dependencies]
python = "^3.11"
Django = "^4.2"
Markdown = "^3.4"
django-cors-headers = "^3.14"
django-environ = "^0.10"
django-filter = "^23.2"
django-redis = "^5.2"
djangorestframework = "^3.14"
djangorestframework-camel-case = "^1.4"
drf-spectacular = "^0.25"
psycopg2-binary = "^2.9"
sentry-sdk = "^1.21"

[tool.poetry.dev-dependencies]
autopep8 = "^2.0"
django-debug-toolbar = "^4.0"
factory-boy = "^3.2"
flake8 = "^6.0"
flake8-isort = "^6.0"
ipython = "^8.13"
isort = "^5.12"
mypy = "^1.2"
pre-commit = "^2.21"
pytest = "^7.3"
pytest-cov = "^4.0"
pytest-django = "^4.5"
pytest-mock = "^3.10"

[build-system]
build-backend = "poetry.core.masonry.api"
requires = ["poetry-core>=1.0.0"]
