# Generated by Django 3.1.6 on 2021-02-06 08:58

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AuthToken',
            fields=[
                ('key', models.CharField(max_length=40, primary_key=True, serialize=False, verbose_name='Key')),
                ('user_agent', models.CharField(blank=True, max_length=1000, verbose_name='User Agent')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Created at')),
                ('expires_at', models.DateTimeField(verbose_name='Expires at')),
            ],
            options={
                'verbose_name': 'Auth Token',
                'verbose_name_plural': 'Auth Tokens',
            },
        ),
    ]
